members-only/config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'

  get    'signin'  => 'sessions#new'
  post   'signin'  => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :users, only: :show
  resources :posts, only: [:new, :create, :index]

end

members-only/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	validates :body, presence: true, length: { in: 1..150 }
end

members-only/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	
	before_save { self.email = email.downcase }
	before_create :save_token


	validates :username, presence: true, uniqueness: true, length: { in: 5..20 }
	validates :email, presence: true, uniqueness: { case_sensitive: false },
										length: { in: 5..30 }

	has_secure_password
	validates :password, length: { in: 8..30 }

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	private
		def save_token
			self.remember_token = User.digest(User.new_token)
		end
end

members-only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user

  def sign_in(user)
  	cookies.permanent[:remember_token] = User.new_token
    cookies.permanent.signed[:user_id] = user.id
    user.update_attribute(:remember_token, User.digest(cookies.permanent[:remember_token]))
    session[:user_id] = user.id
    current_user = user
	end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.remember_token == User.digest(cookies.permanent[:remember_token])
        @current_user = user
      end
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    @current_user.update_attribute(:remember_token, nil)
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
    session.delete(:user_id)
    current_user = nil
  end

  def signed_in_user
    unless signed_in?
      flash[:danger] = "Only members can write posts! Sign in if you're a member."
      redirect_to signin_path
    end
  end
end

members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user, only: [:new, :create]
	
	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.create(post_params)
		if @post.save
			flash[:success] = 'Post created!'
			redirect_to posts_path
		else
			flash.now[:error] = 'Post must be between 5 to 150 characters!'
			render 'new'
		end
	end

	def index
		@posts = Post.all
	end

	private
		def post_params
			params.require(:post).permit(:body)
		end
end

members-only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		flash[:success] = 'Log In Successful!'
  		sign_in user
  		redirect_to user
  	else
  		flash.now[:error] = 'Log in Failed!'
  		render 'new'
  	end
  end

  def destroy
    sign_out if signed_in?
    flash[:success] = 'Logged Out! Until next time...'
    redirect_to root_path
  end
end

members-only/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

members-only/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
  	@user = User.find(params[:id])
  end

  private

end

members-only/app/helpers/application_helper.rb
module ApplicationHelper
end

members-only/app/helpers/posts_helper.rb
module PostsHelper
end

members-only/app/helpers/sessions_helper.rb
module SessionsHelper
end

members-only/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

members-only/app/helpers/users_helper.rb
module UsersHelper
end

members-only/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |message_type, message| %>
	<%= message %>
<% end %>
<%= link_to "Home", root_path %>
<%= link_to "All Posts", posts_path %>
<%= link_to "Write New Post", new_post_path %>

<% if signed_in? %>
	<%= link_to "Profile", current_user %>
	<%= link_to "Sign Out", signout_path, method: "delete" %>
<% else %>
	<%= link_to "Sign In", signin_path %>
<% end %>

<%= yield %>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

members-only/app/views/posts/index.html.erb
<h1>All Posts:</h1>
<% @posts.each do |post| %>
	<ul>
		<li>
			<%= post.body %>
		</li>
		
		<li>
			<% if signed_in? %>
				Written By: <%= post.user.username %>
			<% end %>
		</li>
	</ul>
<% end %>

members-only/app/views/posts/new.html.erb
<h1>Create New Post:</h1>
<%= form_for @post do |f| %>
	<%= f.label :body %>
	<%= f.text_area :body, cols: "50", rows: "3" %>

	<%= f.submit "Submit Post" %> 
<% end %>

members-only/app/views/static_pages/home.html.erb
<h1>Members Only Clubhouse</h1>

<% if signed_in? %>
	<h2>Welcome <%= current_user.username %>!</h2>
<% else %>
	<h2>Welcome!</h2>
<% end %>

<p>More content to come...</p>

members-only/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.username %>